name: Deploy to VPS

on:
    release:
        types: [published]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Deploy to VPS
              uses: appleboy/ssh-action@v0.1.5
              with:
                  host: ${{ secrets.VPS_IP }}
                  username: ${{ secrets.VPS_USER }}
                  password: ${{ secrets.VPS_PASSWORD }}
                  port: ${{ secrets.VPS_PORT }}
                  script: |
                      if [ -d "/image/admin" ]; then
                        rm -rf /image/admin
                      fi
                      git clone https://Baguette42:${{ secrets.GITHUB_TOKEN }}@github.com/Pa3eAnnee/admin-panel.git /image/admin
                      cd /image/admin
                      docker stop web-1
                      docker system prune -af --volumes
                      docker-compose up -d